from rich import print
import os
import datetime 

# Ask for file name
print("\nMade by [cyan]Vincuska#8137[/cyan]")
print("[bright_black]Multilanguage codes may be decoded with errors[/bright_black]\n")

while True:
    try:
        filename = input("File name (only .txt): ")
        if filename.strip():  # check if input is not empty or only contains spaces
            if filename.endswith(".txt"):
                with open(filename, 'r') as file:
                    filedata = file.read()
                    if len(filedata) == 0:
                        print("\n[red]File empty![/red]\n")
                    else:
                        break
            else:
                print("\n[red]File name not ending with .txt![/red]\n")
        else:
            print("\n[red]Input needed![/red]\n")
    except KeyboardInterrupt:
        print("\n[red]Bye![/red]\n")
        break
    except FileNotFoundError:
        print("\n[red]File not found![/red]\n")

filedata = filedata.replace('x41', 'A')
filedata = filedata.replace('x42', 'B')
filedata = filedata.replace('x43', 'C')
filedata = filedata.replace('x44', 'D')
filedata = filedata.replace('x45', 'E')
filedata = filedata.replace('x46', 'F')
filedata = filedata.replace('x47', 'G')
filedata = filedata.replace('x48', 'H')
filedata = filedata.replace('x49', 'I')
filedata = filedata.replace('x4a', 'J')
filedata = filedata.replace('x4b', 'K')
filedata = filedata.replace('x4c', 'L')
filedata = filedata.replace('x4d', 'M')
filedata = filedata.replace('x4e', 'N')
filedata = filedata.replace('x4f', 'O')
filedata = filedata.replace('x4A', 'J')
filedata = filedata.replace('x4B', 'K')
filedata = filedata.replace('x4C', 'L')
filedata = filedata.replace('x4D', 'M')
filedata = filedata.replace('x4E', 'N')
filedata = filedata.replace('x4F', 'O')
filedata = filedata.replace('x50', 'P')
filedata = filedata.replace('x51', 'Q')
filedata = filedata.replace('x52', 'R')
filedata = filedata.replace('x53', 'S')
filedata = filedata.replace('x54', 'T')
filedata = filedata.replace('x55', 'U')
filedata = filedata.replace('x56', 'V')
filedata = filedata.replace('x57', 'W')
filedata = filedata.replace('x58', 'X')
filedata = filedata.replace('x59', 'Y')
filedata = filedata.replace('x5a', 'Z')
filedata = filedata.replace('x5A', 'Z')
filedata = filedata.replace('x61', 'a')
filedata = filedata.replace('x62', 'b')
filedata = filedata.replace('x63', 'c')
filedata = filedata.replace('x64', 'd')
filedata = filedata.replace('x65', 'e')
filedata = filedata.replace('x66', 'f')
filedata = filedata.replace('x67', 'g')
filedata = filedata.replace('x68', 'h')
filedata = filedata.replace('x69', 'i')
filedata = filedata.replace('x6a', 'j')
filedata = filedata.replace('x6b', 'k')
filedata = filedata.replace('x6c', 'l')
filedata = filedata.replace('x6d', 'm')
filedata = filedata.replace('x6e', 'n')
filedata = filedata.replace('x6f', 'o')
filedata = filedata.replace('x6A', 'j')
filedata = filedata.replace('x6B', 'k')
filedata = filedata.replace('x6C', 'l')
filedata = filedata.replace('x6D', 'm')
filedata = filedata.replace('x6E', 'n')
filedata = filedata.replace('x6F', 'o')
filedata = filedata.replace('x70', 'p')
filedata = filedata.replace('x71', 'q')
filedata = filedata.replace('x72', 'r')
filedata = filedata.replace('x73', 's')
filedata = filedata.replace('x74', 't')
filedata = filedata.replace('x75', 'u')
filedata = filedata.replace('x76', 'v')
filedata = filedata.replace('x77', 'w')
filedata = filedata.replace('x78', 'x')
filedata = filedata.replace('x79', 'y')
filedata = filedata.replace('x7a', 'z')
filedata = filedata.replace('x7A', 'z')
filedata = filedata.replace('x40', '@')
filedata = filedata.replace('x5b', '[')
filedata = filedata.replace('x5d', ']')
filedata = filedata.replace('x5e', '^')
filedata = filedata.replace('x5f', '_')
filedata = filedata.replace('x60', '`')
filedata = filedata.replace('x7b', '{')
filedata = filedata.replace('x7d', '}')
filedata = filedata.replace('x7c', '|')
filedata = filedata.replace('x7e', '~')
filedata = filedata.replace('x5B', '[')
filedata = filedata.replace('x5D', ']')
filedata = filedata.replace('x5E', '^')
filedata = filedata.replace('x5F', '_')
filedata = filedata.replace('x60', '`')
filedata = filedata.replace('x7B', '{')
filedata = filedata.replace('x7D', '}')
filedata = filedata.replace('x7C', '|')
filedata = filedata.replace('x7E', '~')
filedata = filedata.replace('x20',' ')
filedata = filedata.replace('x21','!')
filedata = filedata.replace('x22', '"')
filedata = filedata.replace('x23', '#')
filedata = filedata.replace('x24', '$')
filedata = filedata.replace('x25', '%')
filedata = filedata.replace('x26', '&')
filedata = filedata.replace('x27', "'")
filedata = filedata.replace('x28', '(')
filedata = filedata.replace('x29', ')')
filedata = filedata.replace('x2a', '*')
filedata = filedata.replace('x2b', '+')
filedata = filedata.replace('x2c', ',')
filedata = filedata.replace('x2d', '-')
filedata = filedata.replace('x2e', '.')
filedata = filedata.replace('x2f', '/')
filedata = filedata.replace('x3a', ':')
filedata = filedata.replace('x3b', ';')
filedata = filedata.replace('x3c', '<')
filedata = filedata.replace('x3d', '=')
filedata = filedata.replace('x3e', '>')
filedata = filedata.replace('x3f', '?')
filedata = filedata.replace('x2A', '*')
filedata = filedata.replace('x2B', '+')
filedata = filedata.replace('x2C', ',')
filedata = filedata.replace('x2D', '-')
filedata = filedata.replace('x2E', '.')
filedata = filedata.replace('x2F', '/')
filedata = filedata.replace('x3A', ':')
filedata = filedata.replace('x3B', ';')
filedata = filedata.replace('x3C', '<')
filedata = filedata.replace('x3D', '=')
filedata = filedata.replace('x3E', '>')
filedata = filedata.replace('x3F', '?')
filedata = filedata.replace('x4f', 'O')
filedata = filedata.replace('x4F', 'O')
filedata = filedata.replace('x30', '0')
filedata = filedata.replace('x31', '1')
filedata = filedata.replace('x32', '2')
filedata = filedata.replace('x33', '3')
filedata = filedata.replace('x34', '4')
filedata = filedata.replace('x35', '5')
filedata = filedata.replace('x36', '6')
filedata = filedata.replace('x37', '7')
filedata = filedata.replace('x38', '8')
filedata = filedata.replace('x39', '9') # OCTAL -->
filedata = filedata.replace('101', 'A')
filedata = filedata.replace('102', 'B')
filedata = filedata.replace('103', 'C')
filedata = filedata.replace('104', 'D')
filedata = filedata.replace('105', 'E')
filedata = filedata.replace('106', 'F')
filedata = filedata.replace('107', 'G')
filedata = filedata.replace('110', 'H')
filedata = filedata.replace('111', 'I')
filedata = filedata.replace('112', 'J')
filedata = filedata.replace('113', 'K')
filedata = filedata.replace('114', 'L')
filedata = filedata.replace('115', 'M')
filedata = filedata.replace('116', 'N')
filedata = filedata.replace('117', 'O')
filedata = filedata.replace('120', 'P')
filedata = filedata.replace('121', 'Q')
filedata = filedata.replace('122', 'R')
filedata = filedata.replace('123', 'S')
filedata = filedata.replace('124', 'T')
filedata = filedata.replace('125', 'U')
filedata = filedata.replace('126', 'V')
filedata = filedata.replace('127', 'W')
filedata = filedata.replace('130', 'X')
filedata = filedata.replace('131', 'Y')
filedata = filedata.replace('132', 'Z')
filedata = filedata.replace('141', 'a')
filedata = filedata.replace('142', 'b')
filedata = filedata.replace('143', 'c')
filedata = filedata.replace('144', 'd')
filedata = filedata.replace('145', 'e')
filedata = filedata.replace('146', 'f')
filedata = filedata.replace('147', 'g')
filedata = filedata.replace('150', 'h')
filedata = filedata.replace('151', 'i')
filedata = filedata.replace('152', 'j')
filedata = filedata.replace('153', 'k')
filedata = filedata.replace('154', 'l')
filedata = filedata.replace('155', 'm')
filedata = filedata.replace('156', 'n')
filedata = filedata.replace('157', 'o')
filedata = filedata.replace('160', 'p')
filedata = filedata.replace('161', 'q')
filedata = filedata.replace('162', 'r')
filedata = filedata.replace('163', 's')
filedata = filedata.replace('164', 't')
filedata = filedata.replace('165', 'u')
filedata = filedata.replace('166', 'v')
filedata = filedata.replace('167', 'w')
filedata = filedata.replace('170', 'x')
filedata = filedata.replace('171', 'y')
filedata = filedata.replace('172', 'z')
filedata = filedata.replace('100', '@') 
filedata = filedata.replace('133', '[')
filedata = filedata.replace('135', ']')
filedata = filedata.replace('136', '^')
filedata = filedata.replace('137', '_')
filedata = filedata.replace('140', '`')
filedata = filedata.replace('173', '{')
filedata = filedata.replace('175', '}')
filedata = filedata.replace('174', '|')
filedata = filedata.replace('176', '~')
filedata = filedata.replace('40', ' ') 
filedata = filedata.replace('41', '!')
filedata = filedata.replace('42', '"')
filedata = filedata.replace('43', '#')
filedata = filedata.replace('44', '$')
filedata = filedata.replace('45', '%')
filedata = filedata.replace('46', '&')
filedata = filedata.replace('47', "'")
filedata = filedata.replace('50', '(')
filedata = filedata.replace('51', ')')
filedata = filedata.replace('52', '*')
filedata = filedata.replace('53', '+')
filedata = filedata.replace('54', ',')
filedata = filedata.replace('55', '-')
filedata = filedata.replace('56', '.')
filedata = filedata.replace('57', '/')
filedata = filedata.replace('72', ':')
filedata = filedata.replace('73', ';')
filedata = filedata.replace('74', '<')
filedata = filedata.replace('75', '=')
filedata = filedata.replace('76', '>')
filedata = filedata.replace('77', '?')
filedata = filedata.replace('60', '0')
filedata = filedata.replace('61', '1')
filedata = filedata.replace('62', '2')
filedata = filedata.replace('63', '3')
filedata = filedata.replace('64', '4')
filedata = filedata.replace('65', '5')
filedata = filedata.replace('66', '6')
filedata = filedata.replace('67', '7')
filedata = filedata.replace('70', '8')
filedata = filedata.replace('71', '9')

filedata = filedata.replace('\\', '')

decoded_filename = "decoded.txt"
with open(decoded_filename, 'w') as file:
  file.write(filedata)

print(f"\n[green]Decoded and saved to [/green][cyan]{os.path.abspath(decoded_filename)}[/cyan]")